### ISSUE TITLE
LA Feedback

### ISSUE THREAD

**Issue by msaperst** [msaperst/snnap#527]
- [x] Modify 'Jobs' Drop Down (#526)
  - [x] New request to hire - change to 'Create new job'
  - [x] My Hire requests - change to 'My jobs'
  - [x] My hire request applications - (is this supposed to be the applications Ive sent out to other togs or is it supposed to be the applications I've received for my jobs I've posted?) Maybe make a drop down for both of those options? Name them 'Applications received' and 'Jobs I've applied for'
- [x] When you click 'new request to hire': Add a new drop down list named 'Looking for' -2nd photographer - Lead Photographer - Assistant - Photobooth Attendant (#604)
- [x] Under 'Job type' add - Studio Work -Portraits (#526)
- [x] When you click the up and down arrows next to 'pay' have them go up by $1 increments (#526)
- [x] For duration, when i toggle back and forth between 'hours' and 'range' the 'hours' stays highlighted. I think when you click to 'range' it should be highlighted (#634)
- [x] Change the 'Equipment needed' drop down to be a fill in the box and label is: 'Prefered Equipment' That way the poster can say if they prefer cannon, nikon or whatever they want (#634)
- [x] For skills needed I would change the options to:  (#526)
  - Off Camera Flash
  - Comfortable photographing by themselves (this is in reference to photographing separately from the lead when doing the groom shots etc)
  - Natural Light
  - Post Production Editing (this covers retouch, color correction etc)
- [x] Add extra field for comments when submitting application (#636)
